### ISSUE TITLE
Bad link on /pages/guides/contribute.html

### ISSUE THREAD

**Issue by stamminator** [rangle/augury-site#88]
The link on the text "ARCHITECTURE guide" has the same href as the "README just for developers" link next to it. It should go to https://augury.angular.io/pages/guides/architecture.html instead.

![augury docs wrong link](https://user-images.githubusercontent.com/10633170/36398326-8f4b481c-1594-11e8-8b8a-c87dce990622.gif)

Side-note: I would have happily fixed the link myself and submitted a PR, but I couldn't figure out where this docs folder that the actual page markup is stored in is located. For instance, the `../docs/guide/contribution/contribute` path in https://github.com/rangle/augury.angular.io/blob/staging/src/pages/guides/contribute.ejs seems nowhere to be found in this repo. You guys should store that directory here in the repo as well — unless of course I just missed it :)

**Comment by yallen011** [comment]
fixed. This was fixed in the augury-documentation repo with [PR 85](https://github.com/rangle/augury-documentation/pull/85)
